config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#show", via: :get
  resource :dashboard, only: [:show]
  resources :products
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, :trackable, :recoverable, 
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable


	def full_name
		# first_name.capitalize + " " + last_name.capitalize  
		"#{first_name.capitalize} #{last_name.capitalize}"      	
	end         

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


	before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:username, :email, :password) }
	end

	def configure_permitted_parameters
	  devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:first_name, :last_name, :username, :email, :password, :password_confirmation) }
	end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
	def show
		
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	before_filter :check_loged_in_user
	def show
		
	end

	private
	def check_loged_in_user
		if user_signed_in?
			redirect_to products_path
		end
	end
end

app/controllers/products_controller.rb
class ProductsController <ApplicationController

	before_action :set_products, only: [:show, :update, :edit, :destroy]

	def index
		@products = Product.all
	end

	def show	
	end

	def new
		@product = Product.new
	end

	def create
		@product = Product.new (product_params)
			if @product.save
				flash.notice = "Horray your product is been created"
				redirect_to product_path(@product)
		else
			flash.alert = "You can not create a product"
			redirect_to :new
		end		
	end

	def edit		
	end

	def update
		if @product.update(product_params)
  			redirect_to @product, notice: 'product was successfully uopdated.'
  		else
  			render :edit
  		end
	end

	def destroy
		@product.destroy
		redirect_to products_path
	end

	private

	def set_products
		@product = Product.find(params[:id])
	end

	def product_params
		params.require(:product).permit(:title, :description, :price, :image_url )
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboards/show.html.haml
%p Welcome to my Dahshboard

app/views/homes/show.html.haml
%p{"data-role"=> "description"} Welcome to ShopGan Home
= link_to "Create Account", new_user_registration_path

app/views/layouts/_header.html.haml
- if user_signed_in?
	%li
		%span.welcome 
			Welcome, 
			%strong= link_to current_user.full_name, edit_user_registration_path
	%li= link_to "My Dashboard", dashboard_path
	%li= link_to "Log out", destroy_user_session_path, method: :delete
	%li= link_to "Edit profile", edit_user_registration_path
- else
	%li= link_to 'Log in', new_user_session_path
	%li= link_to 'Register', new_user_registration_path
	

app/views/layouts/application.html.haml
!!!
%html
	%head
		%title Shopgan
		= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
		= javascript_include_tag 'application', 'data-turbolinks-track' => true
		= csrf_meta_tags
	%body
		- flash.each do |name, msg|
			= content_tag :div, msg, id: "flash_#{name}"
		= yield
		= render 'layouts/header'

app/views/products/index.html.haml
%h2 All Products List
%table
  %thead
    %tr
      %th Image
      %th Name
      %th Description
      %th Price
      %th Actions
  %tbody
    - @products.each do |pro|
      %tr
        %td= image_tag "products/#{pro.image_url}"
        %td= pro.title
        %td= pro.description
        %td= pro.price
        %td
          = link_to "Show", product_path(pro)
          = link_to "Delete", product_path(pro), confirm: "Are you sure you want to delete this product?", method: :delete

%p= link_to "Create a New Product", new_product_path, id: "new_prodcut"

app/views/products/new.html.haml
= form_for @product do |f|
  .field
    = f.label :title
    %br/
    = f.text_field :title
  .field
    = f.label :description
    %br/
    = f.text_area :description
  .field
    = f.label :price, "Price (like 2.99)"
    %br/
    = f.number_field :price
  .field
    = f.label :image_url
    %br/
    = f.text_area :image_url
  .actions= f.submit

  %p= link_to "Back", products_path

app/views/products/show.html.haml
%h1{id: @product.id} Showing details of product
%p{"data-role"=> "description"} Product Details

%div Name:
%div= @product.title



%ul.product_info
	%div Name:
	%li.title= @product.title 
	%div Description:
	%li.description= @product.description
	%div Price:
	%li.price= @product.price
	%div Image:
	%li.price= @product.image_url


%br/
%p= link_to "All Product", products_path